### ISSUE TITLE
cdk-notifier produces github url when CI configuration is for self hosted Gitlab

### ISSUE THREAD

**Issue by passbt** [karlderkaefer/cdk-notifier#165]
I'm running cdk-notifier version 2.12.5. My command line looks like the example I gave below. 

`cdk-notifier --ci gitlab --gitlab-url "https://gitlab.example.local" --token "$GITLAB_API_TOKEN"  -l cdk-diff.log --tag-id dev-cdk-diff  --template extendedWithResources`

I then end up with a bad credentials error code (401) an example of the full error message is below.

`time=<date/time> level=fatal msg="GET https://api.github.com/repos/<CI_PROJECT_NAMESPACE>/<CI_PROJECT_NAME>/issues/<CI_MERGE_REQUEST_ID>/comments?per_page=100: 401 bad credentials[]`

To state the obvious: the reason for the bad credentials is because cdk-notifier is trying to connect to Github when it should be trying the --gitlab-url I've specified in the command.

Even if the string generated above respected --gitbal-url specified, the full path isn't correct. For instance the path to self hosted Gitlab api's start at: https://gitlab.example.local/api/v4/

I will continue looking through the source code, but my Go expertise is limited.

**Comment by karlderkaefer** [comment]
You probably have a typo in the command `cdk-notifier -ci gitlab` it should be `cdk-notifier --ci gitlab`

**Comment by karlderkaefer** [comment]
Ok I will try to reproduce it

**Comment by passbt** [comment]
I was missing `--vcs gitlab` from my original command line. The command line below works as expected.

`cdk-notifier --ci gitlab --vcs gitlab --gitlab-url "https://gitlab.example.local" --token "$GITLAB_API_TOKEN"  -l cdk-diff.log --tag-id dev-cdk-diff  --template extendedWithResources`

I should have caught that sooner. It is a little confusing since `vcs` isn't a required parameter and it seems like `ci` and `vcs` are duplicated with one another.

**Comment by karlderkaefer** [comment]
glad that it works as expected. yes agree it's a bit confusing. In some cases the git platform might be different that the CI, e.g. running the pipeline on circleci and you use github as git.
