### ISSUE TITLE
Bitbucket Support

### ISSUE THREAD

**Issue by wernermorgenstern** [karlderkaefer/cdk-notifier#29]
Can this tool also support Bitbucket?

**Comment by karlderkaefer** [comment]
Should be possible if Bitbucket has an API, I personally haven't worked with Bitbucket yet but I will take a look. It will take some time to get familiar with bitbucket and it would also require some refactoring of the code

**Comment by karlderkaefer** [comment]
@wernermorgenstern I have completed the initial draft, I need to a lot of refactoring to make this work, I could not re-use the existing bitbucket client and had to write the client on my own. I need to write more tests and update some more documentation, im gonna release within 10 days, but meanwhile you can already test when you build locally on branch. Feedback appreciated
```
export BITBUCKET_TOKEN="t****"
export BITBUCKET_USER="roflmoflcopter"
export REPO_NAME="cdk-notifier-test"
export REPO_OWNER="roflmoflcopter"
export BITBUCKET_PR_ID=1

git checkout support-bitbucket
go build && ./cdk-notifier -l data/cdk-small.log --vcs bitbucket --tag-id next

> INFO[0000] Created comment with id 308183615 and tag id next https://bitbucket.org/roflmoflcopter/cdk-notifier-test/pull-requests/1/_/diff#comment-308183615
```
