### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by napalm684** [karlderkaefer/cdk-notifier#40]
I have interest in adding Gitlab support. Would you be amenable to this? Starting the conversation here per your Medium post.

**Comment by napalm684** [comment]
FYI my fork has this functionality now (quick and dirty replacement). I would really like to work with you on integrating it into your upstream project.

https://github.com/napalm684/cdk-notifier

**Comment by karlderkaefer** [comment]
@napalm684 sorry answering that late, I was out several weekends, festival, sickness and holiday. I have released new version https://github.com/karlderkaefer/cdk-notifier/pull/32 today with final refactoring. Thanks for your constribution. Would be great if you can add gitlab support. If you have questions let me know

**Comment by napalm684** [comment]
@karlderkaefer will do. I have submitted a request to keep the fork I have separate temporarily so I can re-fork your upstream into a new copy and apply the new VCS additions.

**Comment by karlderkaefer** [comment]
@napalm684 please reopen the PR I messed up the merge

**Comment by napalm684** [comment]
@karlderkaefer done

**Comment by napalm684** [comment]
Thx @karlderkaefer pleasure working with you!

**Comment by karlderkaefer** [comment]
same good job!
