### ISSUE TITLE
Suggestion/Issue IAM Statement Changes

### ISSUE THREAD

**Issue by napalm684** [karlderkaefer/cdk-notifier#41]
On the first run of a cdk deployment, the IAM statement changes table in the log is displayed. Not sure if this is a gitlab/github markdown specific issue or not, but documenting this to discuss.

![image](https://user-images.githubusercontent.com/8197405/176944209-336340ec-182d-4cf1-9d89-7ae7d98ed52e.png)

My thought is to suppress the table if it is in the log to reduce noise in the comment posted. Leave the "note" at the end `(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)` with maybe a link to the job log for folks to look closer there?

**Comment by karlderkaefer** [comment]
@napalm684 Could you give a more specific example? To illustrate the issue better add a test log file would help like https://github.com/karlderkaefer/cdk-notifier/blob/main/data/cdk-multistack.log I would like to keep IAM state changes visibile in the logs in general
