### ISSUE TITLE
Include the IAM Stament Changes as part of the message posted to Github

### ISSUE THREAD

**Issue by patoroco** [karlderkaefer/cdk-notifier#65]
Hi,

running the command `cdk diff --profile my_profile MyStack` returns the differences in the resources, but at the same time, if there are some changes in the `IAM Staments`, it's showing in the following way:
![image](https://user-images.githubusercontent.com/701909/203321699-818f559f-cbb6-480c-af69-28877ab9357b.png)

What would be the best way to include these changes as part of the comment that `cdk-notifier` does in the PRs?

**Comment by karlderkaefer** [comment]
Just to understand, so you would expect, if there are only IAM Statement Changes they should be also visible on diff on PR? Could on clarify on what inputs (logs) you would expect which output (content of comment)?
The best way is to start adding a test https://github.com/karlderkaefer/cdk-notifier/blob/a3c721a3bf7fb3328acab838b0bf13b00e45336b/transform/transformer_test.go#L8-L12  
you can add an example log to data folder. And then check towards expected output.

**Comment by karlderkaefer** [comment]
actually it should post the comment if there is any `IAM Statement Change` string in log https://github.com/karlderkaefer/cdk-notifier/blob/a3c721a3bf7fb3328acab838b0bf13b00e45336b/provider/api.go#L50-L53

**Comment by karlderkaefer** [comment]
closing because no response
